### ISSUE TITLE
Bug about Russian map

### ISSUE THREAD

**Issue by amethyst-asuka** [xieguigang/Data.GIS#1]
![untitled](https://cloud.githubusercontent.com/assets/16539191/18815879/65f98a9a-836f-11e6-901e-70baaa94860c.png)
![2](https://cloud.githubusercontent.com/assets/16539191/18815882/6cdfbfe6-836f-11e6-8151-a6c6ff47d9ab.png)

The Russian country land on the output map its position is shifting towards to the  the Arctic

**Comment by xieguigang** [comment]
yes, i've noticed this problem, to day I will fix this bug

**Comment by xieguigang** [comment]
now the bugs fixed in the latest source code!
